### ISSUE TITLE
Always uses count?

### ISSUE THREAD

**Issue by JustMikey** [lucasas/will_paginate_mongoid#18]
Hello, I am really a newbie so maybe I am about to say something foolish but as far as I understand this gem always uses 'self.count' for calculating the total amount of entries and therefore there is no 'total_entries' method for pagination which is not convinient in many ways for perfomance. So, if what i've said correct, are you going to fix it somehow?

**Comment by hayksaakian** [comment]
If you implement a fix yourself, I'm sure the author would not mind a pull request :)

**Comment by lucasas** [comment]
Hi @JustMikey I didn't really get your point here. Can you give some example.
