### ISSUE TITLE
gem depends mongoid version only 2.2.2 ?

### ISSUE THREAD

**Issue by daigong** [lucasas/will_paginate_mongoid#4]
Hello,

Thanks for u gem, It 's very cool,

but I have a problem , I use mongoid (version is 2.3.4) ,but will_paginate_mongo use mongid 2.2.2
###### 

Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    will_paginate_mongoid (>= 0) ruby depends on
      mongoid (~> 2.2.2) ruby

```
mongoid (2.3.4)
```
######

**Comment by lucasas** [comment]
Thanks for use my gem.

And thanks for your commentaries about it.

What version are you trying to install? Will Paginate Mongoid 1.0.3
supports Mongoid 2.4.

There is not yet support for Mongoid 3.0

Regards.

Lucas Ap. Souza

On 15 February 2012 00:45, ReiDai <
reply@reply.github.com

**Comment by daigong** [comment]
last time I try to use mongoid (version is 2.3.4)  and  install will_paginate_mongo , It can not work, error info:

##########################################

Bundler could not find compatible versions for gem "mongoid":
In Gemfile:
will_paginate_mongoid (>= 0) ruby depends on
mongoid (~> 2.2.2) ruby

##########################################

now, I update my mongoid gem version to 2.4.4,and use will_paginate_mongo (1.0.3),all is ok. : )

Thanks

**Comment by lucasas** [comment]
Cool...

Thanks
