### ISSUE TITLE
Gem will not install in JRuby

### ISSUE THREAD

**Issue by glongman** [lucasas/will_paginate_mongoid#5]
There is a runtime dep on bson_ext in the gemspec. bson_ext is native and will not install into JRuby.

please see the comments I've added here:

https://github.com/lucasas/will_paginate_mongoid/blob/94db8979a71efa61382f0a675d071ba7a1f63ecf/will_paginate_mongoid.gemspec

thanks

**Comment by glongman** [comment]
see

https://github.com/lucasas/will_paginate_mongoid/pull/6

**Comment by lucasas** [comment]
Thanks glongman for the pull request :D...I`m generating version 1.0.5

**Comment by glongman** [comment]
Thanks very much for the quick response!

Cheers,

Geoff
