### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by FRickReich** [lucasas/will_paginate_mongoid#7]
i'd really like an example of how it works and how its implemented, because i cant seem to get it to work, always ending up in a 
undefined method `total_pages' for #Array:0x2ab57f6ca3b8
in my sinatra app.

**Comment by FRickReich** [comment]
after 3 hours of fiddling i found out that the pagination has to go below .all() because the class and its content has to exist first...i either am stupid or found something you should put into the readme, and i think you should still make a little example instead of linking to will_paginate ;)

**Comment by dhf0820** [comment]
I agree with putting an actual example in using Mongoid.
