### ISSUE TITLE
Mongoid 3.x support

### ISSUE THREAD

**Issue by cimm** [lucasas/will_paginate_mongoid#8]
Any change of supporting the newest release of Mongoid 3.x? The new release isn't backwards compatible so it might involve a bit more work to update the gem.

**Comment by lucasas** [comment]
Hi Simon, I intend to do this on the next weekend. Actually, I didnt test with Mongoid 3.x yet.

Did you do some tests? If so, can you show me the errors, please?

Regards.

**Comment by cimm** [comment]
Hi Lucas. Thanks, that's great news. I am looking to upgrade our application to Mongoid 3.x but we have 2 dependencies, one being this will_paginate_mongoid gem. The other being carrierwave-mongoid. I tried upgrading but carrierwave-mongoid doesn't seem ready so it's a no go at the moment.

**Comment by lucasas** [comment]
No problem Simon.

I'll do a simple test on the next weekend, fix some issues and generate a
new version.

Anyway, thank you :D

Regards.

Lucas Ap. Souza

**Comment by lucasas** [comment]
Now, version 1.1.0 supports Mongoid 3.0

**Comment by cimm** [comment]
@lucasas Great, thanks a lot. Upgrading our application to Mongoid 3...
