### ISSUE TITLE
Maybe can work in mongoid (3.0.3)

### ISSUE THREAD

**Issue by daigong** [lucasas/will_paginate_mongoid#9]
Hello,

I found in will_paginate_mongoid.gemspec set s.add_runtime_dependency "mongoid", "~> 2.4" , 

Now mongoid version is aleady 3.0.x ,

I update my mongoid version to 3.0.3 and fork your will_paginate_mongoid. update the will_paginate_mongoid.gemspec file,

remove the version code, Use will_paginate_mongoid in mongoid(3.0.3) , It 's seem all ok . :P........

**Comment by lucasas** [comment]
Hello ReiDai,

It's wonderful...Can you make a pull request, please?

Thank you.

Lucas Ap. Souza

**Comment by daigong** [comment]
OK, I aleady pull request.

I just update the will_paginate_mongoid.gemspec file ... 

just seem ok... 
-_-.....  Do more test ,plz

**Comment by lucasas** [comment]
Now, version 1.1.0 supports Mongoid 3.0
